"""
AI Study Tips Page — Select a grade record, get 5 personalised tips
"""
import streamlit as st
import pandas as pd
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).parent.parent))
from utils.api_client import get_all_grades, get_study_tips

# ── CSS ────────────────────────────────────────────────────────────
css_path = Path(__file__).parent.parent / "styles" / "neumorphic.css"
if css_path.exists():
    with open(css_path) as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

st.markdown("# 🤖 AI Study Tips")
st.markdown(
    "<p style='color:#64748B;margin-top:-0.5rem;'>"
    "Powered by Groq LLaMA 3.3 · 70B — personalised tips based on performance</p>",
    unsafe_allow_html=True,
)
st.markdown("---")

# ── LOAD GRADES ────────────────────────────────────────────────────
@st.cache_data(ttl=60)
def _load():
    return get_all_grades()

try:
    grades = _load()
except Exception as e:
    st.error(f"❌ Could not load grades: {e}")
    st.stop()

if not grades:
    st.info("📭 No grade records found. Add some grades first!")
    st.stop()

df = pd.DataFrame(grades)

# ── GRADE SELECTOR ─────────────────────────────────────────────────
st.markdown("### 1️⃣ Select a Grade Record")

# Build display labels
df["label"] = df.apply(
    lambda r: f"ID {r['id']} — {r['student_name']} | {r['subject']} | "
              f"{r['percentage']}% ({r['grade_letter']}) | {r['semester']}",
    axis=1,
)

selected_label = st.selectbox(
    "Choose a grade record to generate tips for:",
    df["label"].tolist(),
    key="tips_select",
)

selected_row = df[df["label"] == selected_label].iloc[0]
grade_id     = int(selected_row["id"])

# ── SELECTED RECORD PREVIEW ────────────────────────────────────────
st.markdown(
    f"""
    <div class="neu-card" style="border-left:4px solid #4F46E5; margin:1rem 0;">
      <div style="display:flex; align-items:center; gap:1rem; flex-wrap:wrap;">
        <div>
          <div style="font-size:1.2rem;font-weight:800;color:#1E293B;">{selected_row['student_name']}</div>
          <div style="color:#64748B;font-size:0.82rem;">Roll: {selected_row['roll_number']} · {selected_row['semester']}</div>
        </div>
        <div style="margin-left:auto;text-align:right;">
          <div style="font-size:2rem;font-weight:800;color:#4F46E5;">{selected_row['percentage']}%</div>
          <div style="font-size:0.75rem;color:#94A3B8;">{selected_row['marks_obtained']}/{selected_row['total_marks']} in {selected_row['subject']}</div>
        </div>
        <div style="background:rgba(79,70,229,0.1);border-radius:20px;padding:0.4rem 1rem;
             font-weight:700;font-size:1.2rem;color:#4F46E5;">{selected_row['grade_letter']}</div>
      </div>
    </div>
    """,
    unsafe_allow_html=True,
)

st.markdown("### 2️⃣ Generate AI Tips")

if st.button("🚀 Get Personalised Study Tips", use_container_width=True, type="primary"):
    with st.spinner("🤖 AI is crafting personalised tips just for you... (may take 10–20 seconds)"):
        try:
            result = get_study_tips(grade_id)
            tips_text = result.get("tips", "")

            st.markdown("---")
            st.markdown("### 💡 Your Study Tips")

            # Render the AI response in a styled card
            st.markdown(
                f"""
                <div class="neu-card">
                  <div style="white-space:pre-wrap;font-size:0.9rem;line-height:1.8;color:#1E293B;">
                  </div>
                </div>
                """,
                unsafe_allow_html=True,
            )
            st.markdown(tips_text)

            # Score context
            st.markdown("---")
            c1, c2, c3 = st.columns(3)
            with c1:
                st.metric("📊 Score", f"{selected_row['percentage']}%")
            with c2:
                st.metric("🏅 Grade", selected_row['grade_letter'])
            with c3:
                status = "✅ Passing" if selected_row['grade_letter'] != "F" else "❌ Failing"
                st.metric("📋 Status", status)

        except Exception as e:
            st.error(f"❌ AI service error: {e}")
            st.info("💡 Make sure your GROQ_API_KEY is set in the backend .env file.")

st.markdown("---")
st.markdown(
    "<p style='color:#94A3B8;font-size:0.78rem;text-align:center;'>"
    "🤖 Tips are generated by Groq LLaMA 3.3 70B · Results may vary · "
    "Always complement AI advice with teacher guidance</p>",
    unsafe_allow_html=True,
)
